theme: jekyll-theme-minimal
logo: https://ctl.s6img.com/society6/img/59mQPsIheee0u9uNmtNx2zZB7oE/w_700/prints/~artwork/s6-original-art-uploads/society6/uploads/misc/3ceabd9d782d402f8cded37b68543897/~~/running-frog-prints.jpg?attempt=0
title: Bioinformatics
